# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 8083
    connection-timeout: 5000
    context-path: /cikers

spring:
    mvc:
        view:
            prefix: /
            suffix: .html
    # 环境 dev|test|prod
    profiles:
        active: dev
    # jackson时间格式化
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    http:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
            enabled: true
    redis:
#        open: false  # 是否开启redis缓存  true开启   false关闭
        database: 0
        host: 148.70.141.228
        port: 6379
        password: maoqin123
        timeout: 6000  # 连接超时时长（毫秒）
        pool:
            max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
            max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
            max-idle: 10      # 连接池中的最大空闲连接
            min-idle: 5       # 连接池中的最小空闲连接


#mybatis
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.cikers.wechat.mall.modules.*.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置
    logic-delete-value: -1
    logic-not-delete-value: 0
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.xxx
    #自定义SQL注入器
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true

cikers:
    wechat:
      appId: wxecd8c4fbea0e9ef1
      appSecret: 6cb51c4ceae9ed6893f6429336515dab
      fitingroomAppId: wx89eb0ae355822f99
      fitingroomAppSecret: f01024f771f8f0212590f1dd43a9cfd7
      grantType: authorization_code
      mchId: 1252369901
      key: RdFN333cKAFRaJVHu4xrt4QX5gADTaYk
      notifyUrl: https://debug.wemall.ps.cikers.com/cikers/wechat/notify
      TRADETYPE: JSAPI
#      host: http://lan.debug.api.ps.cikers.com:10418/mall/v1.0
      host: http://newstack.cikers.com:10422/mall/v1.0
#      host: http://api.ps.cikers.com/mall/v1.0
      exportfile: E:/export
      importfile: E:/import
      weblocation: http\://localhost\:5999/export
      templateId: htK8H-7AKYF1NMVt1qeXjt7ThWP60b9GkBQWDKNCF5k
      earningsTemplateId: qtIC8vfk6qoV1qb03Ok16q4prvJ-ivQaNWSikSy2mn8
      friendOrderTemplateId: qtIC8vfk6qoV1qb03Ok16sp5HjIDGnSuEqREoKmrhaE
      collectOrderTemplateId: Wo9jhtzLah2dBvY-z5qQG0PdtcfEFk8N-YBYV1X45EU
      collectOrderPaymentTemplateId: u1aTZL0Aah_I4Hfn8aQezBoHONKKoqtTD8hSgHPbMOs
      orderExpressTemplateId: QhSZGtZzCHVsUPeLwjLf-ydR0kLveG9yEsXkw9rqKhQ
      #待领取模板消息id
      couponUnclaimedTemplateId: jWQy4fm-gzSAcvctqFWMUR2PEb_n8QOZPQIKvP0RBDE
      #领取成功模板消息id
      couponTakedTemplateId: jWQy4fm-gzSAcvctqFWMUXxBbrfwYU1i9zoW9zu2qn0
      #快到期模板消息id
      couponWillExpiredTemplateId: jWQy4fm-gzSAcvctqFWMUXxBbrfwYU1i9zoW9zu2qn0
      #已过期模板消息id
      couponExpiredTemplateId: jWQy4fm-gzSAcvctqFWMUWM2F9Yf5WapjNqcbKREmIA
      #已使用模板消息id
      couponUsedTemplateId: jWQy4fm-gzSAcvctqFWMUZ8olp-Ie5Jmh2_eqHzenHE

      certPath: C:\\Users\\Administrator\\Desktop\\ciker\procert\\apiclient_cert.p12
      cikerscertPath: C:\\Users\\Administrator\\Desktop\\ciker\procert\\apiclient_cert.p12
      sendRedPacketUrl:  https://api.mch.weixin.qq.com/mmpaymkttransfers/sendredpack
      wxOfficialAppId: wx3bd5aefa8786691d
    server:
#      host:  http://lan.debug.api.ps.cikers.com:10418/mall/v1.0
      host: http://newstack.cikers.com:10422/mall/v1.0
#      host: http://api.ps.cikers.com/mall/v1.0

      cikersHost: https://debug.ps.cikers.com
      jsonFilePath: C:\Users\Administrator\Desktop\文特json\\
      exportfile: E:/export
      importfile: E:/import
      weblocation: http\://localhost\:5999/export
    jwt:
        # 加密秘钥
        secret: f4e2e52034348f86b67cde581c0f9eb5
        # token有效时长，7天，单位秒
        expire: 604800
        header: token

